### ISSUE TITLE
New Drink Selection breaks if colons are in the names

### ISSUE THREAD

**Issue by bhutch29** [bhutch29/abv#121]
The issue is in line 314 of main.go, the findDrinkFromSelection method. It assumes things about colons that we place into the selection display lines.

**Comment by ryanavella** [comment]
Also relevant is line 265 in main.go, which is where we initially present the Untappd results in the search popup in a colon-delimited format.

One solution would be some kind of manager for the Untappd results, which maps those strings to brand/drink pairs. It is a quick fix, but I really hate introducing another global state. We already have viper, gocui, and the modal controller polluting the global scope.

I think the cleaner solution would be to decouple our Untappd logic from gocui as much as possible, and preferably use gocui only for the frontend display. This requires some other kind of feedback about the user's input (e.g. instead of returning the selected string, it returns the index into the slice of strings)

**Comment by ryanavella** [comment]
While we are looking into a more robust solution, one possible quick-and-dirty fix would be to use a multi-character separator like ":::" which is unlikely to appear in a brand or drink name.
