### ISSUE TITLE
Refactor paths in config file to be much simpler

### ISSUE THREAD

**Issue by bhutch29** [bhutch29/abv#70]
Probably too many options for paths. Either need to provide options for EVERYTHING or provide a single cohesive option that we can use as a root for all necessary files.

**Comment by ryanavella** [comment]
I like having one root path for everything. It is less flexible, but I can easily see multiple paths becoming confusing to navigate.

We could tack this on to my existing feature/config-cleanup branch since it hasn't been merged into develop yet, and it already consists of some changes to config.toml.
